name: tests-tickets

on:
  pull_request:
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ububtu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
